research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant youtube links given
    the current year is 2025.
  expected_output: >
    A list with youtube URLs that cover {topic} and the respective description
    with the most relevant information about {topic}. and do have subtitles enabled.Ignore any links that don't
    start with "https://www.youtube.com".
  agent: researcher

summarize_task:
  description: >
    Analyse the information about the {topic} thoroughly to extract the most valuable insights, facts, and recommendations.
    Adhere strictly to the provided schema when extracting information from the input content.
    Ensure that the output matches the field descriptions, types and constraints exactly. Ignore any links that don't
    start with "https://www.youtube.com".
  expected_output: >
    A json with a summary of the {topic} and the most valuable insights, facts, and recommendations. Also add the
    youtube links as references.
  agent: summarizer

write_task:
  description: >
    Review the context you got and craft engaging LinkedIn posts for each key topic.
    Each post should be concise, insightful, and tailored for a professional audience on LinkedIn.
    The LinkedIn post series must include an introductory post, several posts covering each main topic, a post with a code example (if relevant and simplified for LinkedIn), and a concluding post.
  expected_output: >
    A series of structured LinkedIn post drafts, one for each topic.
    Format each post as text, optimized for LinkedIn's platform.
    Note: Please shorten your post and try again. Max 3000 characters.
    Focus on:
      - Engaging opening lines to grab attention.
      - Concise bullet points or short paragraphs for key information.
      - Relevant hashtags for discoverability.
      - A professional yet approachable tone.
      - A clear call to action or question to encourage engagement (optional).
    Avoid using '```' and aim for a professional, LinkedIn-style presentation.
  agent: linkedin_post_writer # Agent designed to write LinkedIn posts
 
